### PR TITLE
feat(hydra-indexer): delete events and extrinsics from SubstrateBlock

### PR DESCRIPTION
**Pull request by tmcgroul**
affects: @subsquid/hydra-common, @subsquid/hydra-indexer, @subsquid/hydra-processor

### CODE REVIEW

**Comment by dzhelezov** [comment]
This one introduces a breaking change, so we can roll it out only when a new /v5/ route is available for new indexers @vistrcm

**Review by dzhelezov — COMMENTED** [review]
LGTM

**Comment by dzhelezov** [comment]
A separate PR will be made to clean up the legacy jsonb fields in the indexer, as it will introduce a breaking change

**Review by eldargab — APPROVED** [review]
LGTM

**Pull request merged**
