### PR TITLE
Working multiimage actions

### PR DESCRIPTION
**Pull request by ma-shulgin**
Allows you to create multiple images and multiple tags via only one action (in previous format) Everything will be published for both amd64 and arm64 arch-s

### CODE REVIEW

**Comment by ma-shulgin** [comment]
need to change to squid credentials

**Comment by ma-shulgin** [comment]
Ready to merge

**Comment by ma-shulgin** [comment]
Tagging as it was previously 
image

**Comment by ma-shulgin** [comment]
Working hasura
image

**Review by dzhelezov — APPROVED** [review]
LGTM

**Comment by ma-shulgin** [comment]
So, @eldargab could you pls run docker-publish action on v5 branch, so that squid-archive-setup becomes usable for m1

**Comment by ma-shulgin** [comment]
Or do I have enough rights for this?

**Comment by ma-shulgin** [comment]
Published and tested👌🏻

**Pull request merged**
